### ISSUE TITLE
Is there a recommended model of Hue lamps?

### ISSUE THREAD

**Issue by UtahDave** [isbm/salt-huelamp#1]
Hi, is there a recommended model of Philips Hue lamps you'd recommend? I see there are 2 generations available. Do both work?

**Comment by isbm** [comment]
@UtahDave Hi. This repo is no longer active and is here for historical reasons (I probably have to archive it, actually). This [module was already "upstreamed"](https://github.com/saltstack/salt/blob/develop/salt/proxy/philips_hue.py) for a while ago.

Answering your question, it works with [this particular model](https://www.amazon.com/Philips-426353-White-Starter-Generation/dp/B00A4EUUO8/). Some people tried with [Hue Go](https://www.amazon.com/Philips-259945-Bloom-Frustration-Free/dp/B00I12YFP0/) while the network device was from the Starter Kit.

Found bugs? PR is welcome (to the upstream). :wink:

**Comment by UtahDave** [comment]
Thanks!
